Search stuff
ninest/dpsms pull request #37
Opened 2023-08-20 02:29 UTC by arjbhat

2023-08-20 19:31 UTC, ninest requested changes

2023-08-20 19:31 UTC, ninest commented on src/app/(main)/search/page.tsx
> +export default async function SearchPage() {
https://nextjs.org/docs/app/api-reference/file-conventions/page#searchparams-optional

The `SearchPage` component can take in `searchParams` which is an object dictionary

inside the `SearchPage`, you can do something like

```tsx
const latitude = int(searchParams.latitude)
const longitude = int(searchParams.longitude)
...
```

Use this to fetch the host listings (calling the search service) then pass them into `SearchResults`

2023-08-20 19:31 UTC, ninest commented on src/app/(main)/search/page.tsx
> +export default async function SearchPage() {
If this is done, SearchResults will not longer have to have "use client"

2023-08-20 19:34 UTC, ninest commented on src/app/(main)/search/page.tsx
> +export default async function SearchPage() {
@arjbhat

2023-08-20 23:17 UTC, ninest commented
@arjbhat All you need to do know is pass the coords/qualifiers to the search service and update the hostListings variable in the search `page.tsx`, then display them in the `SearchResults` component

2023-08-21 00:21 UTC, jamescd18 reviewed
some files missing last line empty

2023-08-21 14:23 UTC, ninest commented on src/app/(main)/search/page.tsx
> +
Doesn't mapbox have a helper function for this?

2023-08-21 14:27 UTC, ninest commented on src/app/(main)/search/page.tsx
> +  }
might wanna pass lat and lon to the search function so you don't have to do any filtering client side

2023-08-22 00:57 UTC, ninest approved these changes

2023-08-22 00:58 UTC, merged